
QUERIES = [
    # ── KEYWORD QUERIES ──────────────────────────────────────────────────────
    {'id':'Q01','type':'keyword','query':'neural network deep learning',
     'challenge':'Short keywords match many docs across AI and Data Science.',
     'relevant_topics':['Artificial Intelligence','Data Science']},
    {'id':'Q02','type':'keyword','query':'blockchain consensus protocol',
     'challenge':'"Consensus" also appears in networking docs.',
     'relevant_topics':['Blockchain','Computer Networks']},
    {'id':'Q03','type':'keyword','query':'quantum entanglement qubit',
     'challenge':'Very specialized; few docs contain all terms together.',
     'relevant_topics':['Quantum Computing']},
    {'id':'Q04','type':'keyword','query':'cloud storage encryption',
     'challenge':'"Encryption" spans Cybersecurity and Cloud Computing.',
     'relevant_topics':['Cloud Computing','Cybersecurity']},
    {'id':'Q05','type':'keyword','query':'IoT sensor network',
     'challenge':'Abbreviation must be expanded; "network" overlaps with Computer Networks.',
     'relevant_topics':['Internet of Things','Computer Networks']},

    # ── NATURAL LANGUAGE QUERIES ──────────────────────────────────────────────
    {'id':'Q06','type':'natural_language',
     'query':'How does machine learning improve cybersecurity threat detection?',
     'challenge':'Cross-topic; long question reduces keyword overlap.',
     'relevant_topics':['Artificial Intelligence','Cybersecurity']},
    {'id':'Q07','type':'natural_language',
     'query':'What are the main challenges of implementing blockchain in supply chains?',
     'challenge':'"Supply chain" may not appear in corpus; needs semantic understanding.',
     'relevant_topics':['Blockchain']},
    {'id':'Q08','type':'natural_language',
     'query':'How do quantum computers outperform classical computers?',
     'challenge':'"Outperform" is not a typical technical keyword.',
     'relevant_topics':['Quantum Computing']},
    {'id':'Q09','type':'natural_language',
     'query':'What is the difference between public and private cloud deployment?',
     'challenge':'Definitional question; docs may not directly compare the two.',
     'relevant_topics':['Cloud Computing']},
    {'id':'Q10','type':'natural_language',
     'query':'How can data science be used to detect network intrusions?',
     'challenge':'Cross-topic bridge between Data Science and Cybersecurity.',
     'relevant_topics':['Data Science','Cybersecurity','Computer Networks']},

    # ── AMBIGUOUS QUERIES ─────────────────────────────────────────────────────
    {'id':'Q11','type':'ambiguous','query':'network security',
     'challenge':'"Network" could mean blockchain, computer network, or neural network.',
     'relevant_topics':['Cybersecurity','Computer Networks','Blockchain']},
    {'id':'Q12','type':'ambiguous','query':'distributed systems',
     'challenge':'Equally relevant to Blockchain, Cloud, and Computer Networks.',
     'relevant_topics':['Blockchain','Cloud Computing','Computer Networks']},
    {'id':'Q13','type':'ambiguous','query':'data mining',
     'challenge':'"Mining" = crypto mining OR data mining technique.',
     'relevant_topics':['Data Science','Blockchain']},
    {'id':'Q14','type':'ambiguous','query':'smart contracts automation',
     'challenge':'"Smart" might pull AI docs; "automation" overlaps with IoT.',
     'relevant_topics':['Blockchain','Internet of Things']},
    {'id':'Q15','type':'ambiguous','query':'edge computing latency',
     'challenge':'"Edge" is key in both IoT and Cloud; "latency" is generic.',
     'relevant_topics':['Internet of Things','Cloud Computing','Computer Networks']},

    # ── NOISY / TYPO QUERIES ──────────────────────────────────────────────────
    {'id':'Q16','type':'noisy','query':'mchine lerning algorythms',
     'challenge':'Three typos — machine, learning, algorithms — all key terms corrupted.',
     'relevant_topics':['Artificial Intelligence','Data Science']},
    {'id':'Q17','type':'noisy','query':'blokchain crytocurency trnsaction',
     'challenge':'Three misspellings in domain-specific vocabulary.',
     'relevant_topics':['Blockchain']},
    {'id':'Q18','type':'noisy','query':'cybr securtiy atack prevntion',
     'challenge':'Heavy noise; all four words contain errors.',
     'relevant_topics':['Cybersecurity']},
    {'id':'Q19','type':'noisy','query':'quantm computng qubit procesing',
     'challenge':'Rare technical vocabulary made harder by misspellings.',
     'relevant_topics':['Quantum Computing']},
    {'id':'Q20','type':'noisy','query':'clod computng servr virtualiztion',
     'challenge':'"clod" instead of "cloud" may confuse spell checker.',
     'relevant_topics':['Cloud Computing']},
]
